# This dockerfile defines the expected runtime environment before the project is installed
FROM ubuntu:latest

# Be sure to install any runtime dependencies
RUN apt-get clean && apt-get update && apt-get install -y \
libboost-program-options1.58.0
